### ISSUE TITLE
on Arduino MEGA 2560?

### ISSUE THREAD

**Issue by ronistiawan** [adafruit/Adafruit-BMP085-Library#13]
How to use this library on Mega 2560? 
do I need to edit the library?

**Comment by bcampetelli** [comment]
I have the same problem. Did you resolved???

**Comment by ronistiawan** [comment]
Yes, I did.. I followed the instructions. and then i made some changes on the GSM.cpp
I also need to hook up 18 and 19 pin of arduino mega to Rx Tx pin on GSM Shield.

**Comment by ronistiawan** [comment]
Yes,I did. what kind off error did you got?

**Comment by bcampetelli** [comment]
I have already solved. I was wrong defining variable that stored pressure
It was int, and must be long.
Sorry by my english
