### ISSUE TITLE
How to measure QNH using BMP085 sensor

### ISSUE THREAD

**Issue by rogeriopimentel** [adafruit/Adafruit-BMP085-Library#15]
Hello,

I would like to do my barometer to measure QNH in Hecto Pascal.
I tested your sample to Arduino but I perceved that pressure is the QFE and I would like know, how to get the QNH values. Other thing, I would like to show it in hPA. Can you help me?
Thank you

Pimentel

**Comment by kovir** [comment]
double sealevel_pressure = (bmp.readSealevelPressure (208) / 100.0F);
Serial.println(sealevel_pressure);

**Comment by Qhergt** [comment]
What about QNH but inHG?

**Comment by samyk** [comment]
inHg = Pa / 3386.39
