### ISSUE TITLE
Two sensors on I2C bus

### ISSUE THREAD

**Issue by Sebenzouz** [adafruit/Adafruit-BMP085-Library#24]
Hello,
For a project, I would like to test the good functioning of a pressure sensor. To do that, I would like to comparate the value returned by the sensor tested with and other pressure sensor. However, I don't know if it is possible to do, because I have to connect the two sensors on the same I2C bus. Is it possible to adress differents requests to each sensors? These two are BMP180.
Thanks a lot,
Seb.

**Comment by samyk** [comment]
From section 4.2 of the [BMP085 datasheet](https://cdn-shop.adafruit.com/datasheets/BST-BMP085-DS000-06.pdf):

> There is an easy way to connect two BMP085 to the same I2C bus: You can use the XCLR input of BMP085 to set one BMP085 part silent while you communicate with the other BMP085 part via I2C and vice versa. The signals can be provided by two digital outputs of the microcontroller, or one digital output and one inverter.
